In [1]:
import numpy as np

In [2]:
var1=np.array([1,2,3,4])

In [3]:
var1

array([1, 2, 3, 4])

In [4]:
type(var1)

numpy.ndarray

In [5]:
var1.dtype

dtype('int32')

In [6]:
varA=[1,1.1,2]
var2=np.array(varA)

In [7]:
var2

array([1. , 1.1, 2. ])

In [8]:
var2.dtype

dtype('float64')

In [9]:
var2.shape

(3,)

In [11]:
var3=np.array([[1.5,2.5],[3.4]], dtype=object)

In [12]:
var3

array([list([1.5, 2.5]), list([3.4])], dtype=object)

In [13]:
var3=np.array([[1.5,2.5],[3,4]], dtype=object)

In [14]:
var3

array([[1.5, 2.5],
       [3, 4]], dtype=object)

In [15]:
var3.shape

(2, 2)

In [16]:
var3[0]

array([1.5, 2.5], dtype=object)

In [18]:
var3[0,0]

1.5

In [19]:
var3[-1,-1]

4

In [20]:
var3[-1,0]="Brian"

In [21]:
var3

array([[1.5, 2.5],
       ['Brian', 4]], dtype=object)

### Alokasi dan Random Array

In [22]:
varA=np.empty(3)

In [23]:
varA

array([1. , 1.1, 2. ])

In [24]:
varB=np.empty((3,2))

In [25]:
varB

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [26]:
5*0.001

0.005

In [27]:
5*1e-3

0.005

In [30]:
#Hindari penggunaan .empty karna tiap kom berbeda hasil
#Pakai zeros
varB=np.zeros((3,2))

In [31]:
varB

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [32]:
varC=np.empty((10,10))

In [33]:
varC

array([[            nan,             nan, 1.78629442e-285,
        4.48114411e-299, 4.43289729e-287,             nan,
        5.49683522e-298, 5.38286300e-295,             nan,
        7.57280209e-307],
       [4.30582753e-294, 1.78005909e-307,             nan,
        3.38307886e-301, 3.43526457e-299, 2.18053323e-289,
                    nan,             nan,             nan,
        7.39421006e-288],
       [1.29014290e-297, 2.00292127e-307, 2.30479211e-291,
        2.54534645e-287,             nan, 3.30276584e-295,
        1.82416773e-304, 1.04525469e-299, 3.36312977e-300,
        6.72487310e-284],
       [            nan, 7.18293551e-289,             nan,
        1.20325087e-290,             nan, 1.86653295e-299,
        5.84015141e-303, 7.73912979e-284, 1.18005355e-288,
        2.29358867e-297],
       [1.85255436e-305, 1.10843567e-301, 3.41497264e-286,
        2.21656514e-287,             nan,             nan,
        4.49216772e-290, 1.38528117e-288,             nan,
           

In [34]:
varD=np.ones((5,3))

In [35]:
varD

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [36]:
varE=np.arange(1,5)

In [37]:
varE

array([1, 2, 3, 4])

In [38]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [39]:
varMin=1
varMax=10
varDelta=2
np.arange(varMin,varMax,varDelta)

array([1, 3, 5, 7, 9])

In [40]:
np.arange(10,2,-2)

array([10,  8,  6,  4])

### Random Numpy

In [43]:
np.random.random(3)

array([0.97967255, 0.58099367, 0.59252269])

In [44]:
np.random.random((3,2))

array([[0.78472299, 0.02943324],
       [0.04384574, 0.02141813],
       [0.98632982, 0.94105428]])